### ISSUE TITLE
Docker Compose UP not working in VSCode Terminal

### ISSUE THREAD

**Issue by Wferr** [Microsoft/vscode-docker#212]
Hello! I have recently encountered in error with the docker compose up command within vscode-docker. For some reason when I run the command during the download images part of the compose-up it errors out. But when I type the same exact command  (ex "docker-compose -f Docker-GLPI\docker-compose.yml up -d --build") into a Command Prompt window it runs fine. I'm using Command Prompt as my terminal. 

I'm running Windows 10 with docker-ce 17.12.0 & vscode 1.19.3 & vscode-docker 0.0.24 

Here is the error:

`
C:\Users\Wferr\docker>docker-compose -f Docker-GLPI\docker-compose.yml up -d --build
Creating network "dockerglpi_default" with the default driver
Pulling sql (mariadb:latest)...
latest: Pulling from library/mariadb
f49cf87b52c1: Downloading [=====================================>             ]  39.47MB/52.6MB
78032de49d65: Download complete
84229c396ea3: Download complete
c992bbf20f4e: Download complete
380e932be3aa: Download complete
8003c6d68fcd: Download complete
603f60c36160: Download complete
37a57af54a5d: Download complete
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 959, in up
  File "compose\project.py", line 452, in up
  File "compose\service.py", line 318, in ensure_image_exists
  File "compose\service.py", line 1081, in pull
  File "compose\progress_stream.py", line 44, in stream_output
  File "compose\progress_stream.py", line 63, in print_output_event
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose

C:\Users\Wferr\docker>
'

The docker-compose that caused it:
`version: '3'

services:

  glpi:
    image: turgon37/glpi
    ports:
      - 8080:80
    volumes:
      - glpi-files:/var/www/files
      - glpi-config:/var/www/config
    links:
      - sql

  sql:
    image: mariadb
    volumes:
      - sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secure

volumes:
  glpi-files:
  glpi-config:
  sql:`

Thanks. Happy to provide any more info.

**Comment by Wferr** [comment]
After a bit more looking into it, it seems to work fine in vscode after it has ran once/downloaded the images from a regular command line window.

**Comment by robertpeteuil** [comment]
@Wferr congrats on finding a workaround. 

You may already know this, but I'll share for others who may see this thread:

- Based on the timing and library when the error is triggered, I suspect there's an ANSI+escape sequence that's not properly implemented by the embedded command prompt.  But, is supported in the external command prompt. 
- Colorama is common Python library, used when writing cross-platform python apps that use color output. Since it fails with IOError, it's failing right when it's trying to write something to the screen, after specifically converting it to windows supported text/format sequence.
- This suspicion is further reinforced by the fact that it occurs when downloading images, which uses text-based scroll bars via ansi-escape codes to show download progress and completion (at least on other platforms).

**Comment by chrisdias** [comment]
@robertpeteuil interesting analysis thanks, @Tyriar any thoughts?

@Wferr do you have a dockerfile and compose file that repros the problem?

**Comment by robertpeteuil** [comment]
@chrisdias Thanks.  I just noticed his error was triggered at the exact point where the progress bar should be deleted (via ansi-escaped-delete/backspace characters) and replaced with `Pull complete`.  It also occurred at the very first instance of this.  I'm referring to this line *where the bar if full and about to be remove):

```
f49cf87b52c1: Downloading [=====================================> ] 39.47MB/52.6MB
```

If my theory is correct, then any compose file that needs to pull images before starting should exhibit this problem.  Here's a short example that should reproduce, provided the "microsoft/iis" image isn't already on the host.  (I don't have Docker and VSCode on a Windows host to test.)

```
version: '2'
services:
  iis:
    image: microsoft/iis
```

**Comment by chrisdias** [comment]
yep, I can repro:

``` bash
docker rmi redis:alpine
docker compose -f docker-compose.yml up -d --build
docker compose -f docker-compose.yml down
```

And here is a `docker-compose.yml` file:

``` yaml
version: '3'

services:
  redis:
    image: "redis:alpine"
```

and the results:

``` console
D:\src\stickerapp>docker-compose -f docker-compose.1.yml up -d --build
Pulling redis (redis:alpine)...
alpine: Pulling from library/redis
ff3a5c916c92: Extracting [=====================>                             ]  884.7kB/2.066MB
aae70a2e6027: Download complete
87c655da471c: Download complete
a0bd51ac7350: Waiting
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 959, in up
  File "compose\project.py", line 452, in up
  File "compose\service.py", line 318, in ensure_image_exists
  File "compose\service.py", line 1081, in pull
  File "compose\progress_stream.py", line 44, in stream_output
  File "compose\progress_stream.py", line 63, in print_output_event
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose
```

I'll submit an issue to vscode.

**Comment by robertpeteuil** [comment]
Thanks for testing, and posting your results.  I'm glad I could help a bit.

Since your results show a failure without a full bar, it may not be an "unsupported" ANSI code, but rather an overflow issue caused by the number of them occurring in rapid succession.

At the TTY level each progress bar update process requires a ton of character writes:
- draw a new `=`
- move the cursor to DL info
- overwrite the download-info with updated info
- move the cursor back for next update

**Comment by robertpeteuil** [comment]
Just an update if anyone checks this. 

This is a Windows issue and unfortunately can't be fixed until new insiders builds start rolling out.  

Thread describes why it occurs in VSCode embedded prompt and not the normal one, and describes the issue in explicit detail:  [Microsoft/vscode#36630 (comment)](https://github.com/Microsoft/vscode/issues/36630#issuecomment-350063413)
