### ISSUE TITLE
Extension not working in Admin

### ISSUE THREAD

**Issue by mlvogel1214** [microsoft/vscode-docker#2175]
Issue Type: <b>Bug</b>

When right click and clicking build image on docker file the build never executes.
The following error code displays:
Activating extension 'ms-azuretools.vscode-docker' failed: The "path" argument must be of type string. Received type undefined. 
Have tried uninstalling and reinstalling extention.  Uninstalled and reinstalled vs code.  Same error.  Error only occurs when in elevated admin mode

Extension version: 1.3.1
VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:22:06.216Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
I have not been able to reproduce the issue. Can you tell me more about your workspace?

**Comment by mlvogel1214** [comment]
I am using vs code in elevated admin mode to build an image and use with portainer to test locally.  I have docker windows installed.  Previously I have been able to simply right click and select build image with the docker extension and it correctly builds my image to use with portainer. Now nothing happens except in console I found the previously listed error.

When manually running build image command i get the following error: 
Command 'Docker Images: Build Image...' resulted in an error (command 'vscode-docker.images.build' not found).  Error only occurs in admin mode. Running in non admin mode executes but fails with error instructing to run in admin mode.

**Comment by bwateratmsft** [comment]
Is there any additional information indicating where the activation error is coming from (stack trace, etc.)? I would expect to see the "command not found" error when activation fails and then you do "build image", but I'm having trouble finding any place where that "path" error could be happening during activation.

**Comment by bwateratmsft** [comment]
I found a place where helpful info is emitted. In the Output tab, there's a section for "Log (Extension Host)", this might tell us the info we need. For example:
![image](https://user-images.githubusercontent.com/36966225/87807729-a3c30180-c826-11ea-82aa-a0824782ea84.png)

**Comment by mlvogel1214** [comment]
ok.  That helps finding some more info


[2020-07-17 11:43:46.714] [exthost] [error] Activating extension ms-azuretools.vscode-docker failed due to an error:
[2020-07-17 11:43:46.714] [exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.join (path.js:375:7)
	at Function.Module._nodeModulePaths (internal/modules/cjs/loader.js:590:37)
	at Module.load (internal/modules/cjs/loader.js:777:23)
	at Module._load (internal/modules/cjs/loader.js:693:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\mvogel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:974:348)
	at Function.i._load (c:\Users\mvogel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:943:839)
	at Function.n._load (c:\Users\mvogel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:940:198)
	at Module.require (internal/modules/cjs/loader.js:820:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Users\mvogel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:33:205)
	at h._loadCommonJSModule (c:\Users\mvogel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:945:34)
	at h._doActivateExtension (c:\Users\mvogel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:835:599)
	at h._activateExtension (c:\Users\mvogel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:834:692)
	at Object.actualActivateExtension (c:\Users\mvogel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:832:453)
	at h._activateExtension (c:\Users\mvogel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:405)
	at c:\Users\mvogel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:83
	at Array.map (<anonymous>)
	at h._activateExtensions (c:\Users\mvogel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:71)
	at c:\Users\mvogel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:176
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by bwateratmsft** [comment]
It looks like this is the same as https://github.com/microsoft/vscode/issues/102751 or https://github.com/microsoft/vscode/issues/102642

**Comment by mlvogel1214** [comment]
Thanks for the info
