### ISSUE TITLE
Remote-Containers Attach to Running Container gives error stream ended with 125

### ISSUE THREAD

**Issue by kzawad1** [microsoft/vscode-docker#2405]
Performing the following:

1. From **Visual Studio Code**, select **View | Command Palette...**.
2. Enter text "Remote-Containers: Attach".
3. Select "Remote-Containers: Attach to Running Container...".
4. Wait for Visual Studio Code to connect to the target and get a list of containers.
5. Select the specific container.
6. Wait for the attach process to execute and the following error to be displayed:

```
[66480 ms] Start: Run in container: /home/user1/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/server.sh --disable-user-env-probe --port 0 --extensions-download-dir /home/user1/.vscode-server/extensionsCache
[70506 ms] Error: stream ended with:125 but wanted:1128865906
        at p (/home/user2/.vscode/extensions/ms-vscode-remote.remote-containers-0.145.0/dist/extension.js:1:247667)
        at /home/user2/.vscode/extensions/ms-vscode-remote.remote-containers-0.145.0/dist/extension.js:1:247837
        at s (/home/user2/.vscode/extensions/ms-vscode-remote.remote-containers-0.145.0/dist/extension.js:1:263154)
        at Socket.<anonymous> (/home/user2/.vscode/extensions/ms-vscode-remote.remote-containers-0.145.0/dist/extension.js:1:263327)
        at Socket.emit (events.js:228:7)
        at endReadableNT (_stream_readable.js:1185:12)
        at processTicksAndRejections (internal/process/task_queues.js:81:21)
[70508 ms] Remote-Containers server terminated (code: 126, signal: null).
```

Why does "Error: stream ended with:125 but wanted:1128865906" mean?  Why is it being reported this way?

**Comment by bwateratmsft** [comment]
This would be an issue with [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers), their repo is [here](https://github.com/microsoft/vscode-remote-release). Can you open this there?
