### ISSUE TITLE
Travis CI will not build

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/vscode-docker#289]
Not sure if this only affects forks or not? @StephenWeatherford, any ideas?
```
Created: /home/travis/build/rcjsuen/vscode-docker/vscode-docker-0.0.28.vsix
[13:53:16] Finished 'package' after 15 s

The command "gulp package" exited with 0.

1.08s
$ gulp upload-vsix
[13:53:17] Using gulpfile ~/build/rcjsuen/vscode-docker/gulpfile.js
[13:53:17] Starting 'upload-vsix'...
[13:53:17] 'upload-vsix' errored after 464 μs
[13:53:17] Error: Credentials must be provided when creating a service client.
    at Function.StorageServiceSettings.createFromEnvironment (/home/travis/build/rcjsuen/vscode-docker/node_modules/azure-storage/lib/common/services/storageservicesettings.js:182:9)
    at Function.StorageServiceClient.getStorageSettings (/home/travis/build/rcjsuen/vscode-docker/node_modules/azure-storage/lib/common/services/storageserviceclient.js:918:53)
    at new BlobService (/home/travis/build/rcjsuen/vscode-docker/node_modules/azure-storage/lib/services/blob/blobservice.core.js:101:53)
    at Object.exports.createBlobService (/home/travis/build/rcjsuen/vscode-docker/node_modules/azure-storage/lib/azure-storage.js:98:10)
    at Gulp.gulp.task (/home/travis/build/rcjsuen/vscode-docker/gulpfile.js:23:42)
    at module.exports (/home/travis/build/rcjsuen/vscode-docker/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/travis/build/rcjsuen/vscode-docker/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/travis/build/rcjsuen/vscode-docker/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/travis/build/rcjsuen/vscode-docker/node_modules/orchestrator/index.js:134:8)
    at /home/travis/build/rcjsuen/vscode-docker/node_modules/gulp/bin/gulp.js:129:20

The command "gulp upload-vsix" exited with 1.

6.99s
$ npm run lint

> vscode-docker@0.0.28 lint /home/travis/build/rcjsuen/vscode-docker
> tslint --project tsconfig.json -t verbose
```

**Comment by StephenWeatherford** [comment]
Are you running this locally?

**Comment by rcjsuen** [comment]
@StephenWeatherford I have a fork of the project and my own Travis CI instance is trying to build it. It seems fair to me that if the environment variables are not defined that it shouldn't try to do any uploading to Azure.
