### ISSUE TITLE
Everything is blank in WSL2 (recent update?)

### ISSUE THREAD

**Issue by mattbell87** [microsoft/vscode-docker#3003]
I have noticed that all of a sudden if I'm working on a docker project in WSL2 the extension appears to be broken:

Video shows it works OK on normal VSCode but not in WSL2:
https://user-images.githubusercontent.com/2722612/122151123-51f58200-cea2-11eb-9b2f-f24a3dbb0c27.mp4

I also noticed this in the console:
![image](https://user-images.githubusercontent.com/2722612/122151391-d3e5ab00-cea2-11eb-9dfc-530ac7dce14e.png)

I have tried resetting settings, uninstalling, reinstalling the extension etc.

**Comment by karolz-ms** [comment]
Cannot reproduce with Docker Desktop 3.4.0, VS Code 1.57.0, Docker VS Code ext 1.13.0 and Windows 10 Enterprise 21H1 build 19043.1052.

@mattbell87 make sure "WSL integration" is enabled for your distro in Docker Desktop settings--I noticed that during upgrade to Desktop 3.4.0 (just released) that was disabled for whatever reason.

**Comment by mattbell87** [comment]
> Cannot reproduce with Docker Desktop 3.4.0, VS Code 1.57.0, Docker VS Code ext 1.13.0 and Windows 10 Enterprise 21H1 build 19043.1052.
> 
> @mattbell87 make sure "WSL integration" is enabled for your distro in Docker Desktop settings--I noticed that during upgrade to Desktop 3.4.0 (just released) that was disabled for whatever reason.

Yeah mine is enabled and my Ubuntu distro is switched on. Docker and docker-compose commands work fine in the WSL2 distro.

**Comment by mattbell87** [comment]
@karolz-ms I can confirm I'm running the same software versions as you.

The only thing I haven't done is install VSCode fresh. But I'd like to help fix the error so that it doesn't happen to others. Open to trying to debug it further if there's anywhere you'd like me to look.

 Any idea what the error in the console means?

**Comment by mattbell87** [comment]
By inserting some breakpoints on $onExtensionActivationError I found the stack if this means anything to someone:

```
SyntaxError: Unexpected token '}'
	at wrapSafe (internal/modules/cjs/loader.js:979:16)
	at Module._compile (internal/modules/cjs/loader.js:1027:27)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
	at Module.load (internal/modules/cjs/loader.js:928:32)
	at Function.Module._load (internal/modules/cjs/loader.js:769:14)
	at Function.i._load (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:103:27790)
	at Function.E._load (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:103:24542)
	at Function.c._load (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:93:59193)
	at Module.require (internal/modules/cjs/loader.js:952:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Object.<anonymous> (/home/matt/.vscode-server/extensions/ms-azuretools.vscode-docker-1.13.0/main.js:22:19)
	at Module._compile (internal/modules/cjs/loader.js:1063:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
	at Module.load (internal/modules/cjs/loader.js:928:32)
	at Function.Module._load (internal/modules/cjs/loader.js:769:14)
	at Function.i._load (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:103:27790)
	at Function.E._load (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:103:24542)
	at Function.c._load (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:93:59193)
	at Module.require (internal/modules/cjs/loader.js:952:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:5:101)
	at f._loadCommonJSModule (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:103:25948)
	at f._doActivateExtension (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:89:12599)
	at f._activateExtension (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:89:11658)
	at Object.actualActivateExtension (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:89:9243)
	at l._activateExtension (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:84:85443)
	at /home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:84:85125
	at Array.map (<anonymous>)
	at l._activateExtensions (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:84:85113)
	at l.activateByEvent (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:84:82447)
	at f._activateByEvent (/home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:89:10142)
	at /home/matt/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostProcess.js:89:20014
```

**Comment by mattbell87** [comment]
More Info: (sorry about the spam!)

It can now confirm on my setup the extension works on v1.12.1 but not v1.13.0.

**Comment by karolz-ms** [comment]
Thank you @mattbell87 this helps. 

It might be a long shot, but can you try deleting  `~/.vscode-server/extensions/ms-azuretools.vscode-docker-1.13.0` and re-installing the Docker extension 1.13.0 in the WSL2 environment again? The theory is something went wrong during extension download and the copy within the WSL2 environment is damaged.

**Comment by mattbell87** [comment]
Yes that worked so it must have been damaged somehow. No one else has had the same issue so far, so I'll close the issue.

Thanks @karolz-ms !
