### ISSUE TITLE
There is an error after executing "Open in Browser" on a running container

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3091]
**OS:** All
**Build Version:** 20210723.6

**Repro Steps:**
1. Navigate the "CONTAINERS" node -> Right click a running container(contains valid ports) -> Select "Open in Browser".
2. Check whether succeed to open the webpage in the browser without any error.

**Expect:**
Succeed to open the webpage in the browser without any error.

**Actual:**
Succeed to open the webpage in the browser with an error.
![Screen Shot 2021-07-27 at 5 30 45 PM](https://user-images.githubusercontent.com/62053665/127133518-b7419251-26fe-448d-8faf-033d88895eb6.png)

**Comment by bwateratmsft** [comment]
I can reproduce. It opens the webpage but shows that error. The error in the Extension Host output window is this:

```
[2021-07-27 13:24:24.570] [exthost] [error] TypeError: data.replace is not a function
    at maskValue (d:\vscode-docker\dist\webpack:\vscode-docker\node_modules\vscode-azureextensionui\out\src\masking.js:98:1)
    at Object.maskUserInfo (d:\vscode-docker\dist\webpack:\vscode-docker\node_modules\vscode-azureextensionui\out\src\masking.js:79:1)
    at handleTelemetry (d:\vscode-docker\dist\webpack:\vscode-docker\node_modules\vscode-azureextensionui\out\src\callWithTelemetryAndErrorHandling.js:214:1)
    at Object.<anonymous> (d:\vscode-docker\dist\webpack:\vscode-docker\node_modules\vscode-azureextensionui\out\src\callWithTelemetryAndErrorHandling.js:91:1)
    at Generator.next (<anonymous>)
    at fulfilled (d:\vscode-docker\dist\webpack:\vscode-docker\node_modules\vscode-azureextensionui\out\src\callWithTelemetryAndErrorHandling.js:9:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) vscode-docker.containers.browse
```
