### ISSUE TITLE
Plugin doesn't install on remote docker container behind proxy with Self-signed certificate

### ISSUE THREAD

**Issue by dovidweisz** [microsoft/vscode-docker#3168]
The title pretty much describes my issue. The installation fails when inside of a docker container using [remote containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers), behind a corporate proxy. 

I've been working on this for a few days so here are some things about my setup you should know:

* I have "Proxy Strict SSL" unchecked in the settings.
* The Self-signed certificate is installed on the host machine.
* The Self-signed certificate is installed on the container.

**This has worked for me in the past, and I don't have this issue with other plugins.**

When i try installing i get a "self signed certificate in certificate chain" error:

```
[2021-08-23 11:23:20.192] [renderer4] [info] Trying to download 'ms-azuretools.vscode-docker' extension locally and install
[2021-08-23 11:23:22.840] [renderer4] [error] ["Error: self signed certificate in certificate chain","    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)","    at TLSSocket.emit (events.js:315:20)","    at TLSSocket._finishInit (_tls_wrap.js:932:8)","    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)"]
```

With `NODE_EXTRA_CA_CERTS` set I get a "socket hang up" error:

```
[2021-08-23 11:07:45.164] [renderer4] [error] ["Error: socket hang up","    at connResetException (internal/errors.js:607:14)","    at TLSSocket.socketOnEnd (_http_client.js:493:23)","    at TLSSocket.emit (events.js:327:22)","    at endReadableNT (internal/streams/readable.js:1327:12)","    at processTicksAndRejections (internal/process/task_queues.js:80:21)"]
```

**Comment by bwateratmsft** [comment]
Probably related to or same as https://github.com/microsoft/vscode/issues/130962. Can you try on Insiders and see if the issue exists?

The Docker extension has no control over its own download and installation so this would be a bug in https://github.com/microsoft/vscode.

**Comment by dovidweisz** [comment]
@bwateratmsft So i should try the insiders build of VSCode itself?

**Comment by bwateratmsft** [comment]
Yes, exactly. The fix for https://github.com/microsoft/vscode/issues/130962 should be in the latest VSCode Insiders builds.

**Comment by dovidweisz** [comment]
Thank you.

That worked.
