### ISSUE TITLE
We don't show errors when unable to log into Docker Hub

### ISSUE THREAD

**Issue by keithdoyle9** [microsoft/vscode-docker#360]
When clicking "refresh" button or expanding the "Docker Hub" section under "Registries", I am always prompted for username and password and my Docker Hub registries never appear. Logging in doesn't provide any messages and never seems to work.

**Comment by jinglouMSFT** [comment]
What happens if you try to login from a command line or docker hub itself?

**Comment by keithdoyle9** [comment]
I can login to Docker Hub just fine via the command line and on hub.docker.com, but even after I log in via command line the VS Code Extension still prompts for password.

**Comment by StephenWeatherford** [comment]
What OS?  Also, if you do command palette -> Developer Tools, do you see any error messages in the output?

**Comment by keithdoyle9** [comment]
Windows 7 - 64-bit

No output at all when trying to log in.

**Comment by keithdoyle9** [comment]
I think I found out what it is. I finally see some output and it looks like our firewall is intercepting the SSL traffic and the cert isn't valid. I'll handle this within my company.

**Comment by StephenWeatherford** [comment]
Thanks!  I'd like to keep this open because we shouldn't be silently failing.

**Comment by StephenWeatherford** [comment]
It's likely this will be fixed by moving to AzureTreeDataProvider (https://github.com/Microsoft/vscode-azuretools/blob/940e63472fc9fd8d4b4d1bd24bc0e2a5ebf8a7d9/ui/src/treeDataProvider/AzureTreeDataProvider.ts#L27) - I believe it does appropriate error handling.

**Comment by keithdoyle9** [comment]
Do you know the URL that the service hits? I need to get it whitelisted in our firewall.

`[Extension Host] RequestError: Error: unable to get local issuer certificate
	at new RequestError (C:\Users\kdoyle\.vscode\extensions\peterjausovec.vscode-docker-0.1.0\node_modules\request-promise-core\lib\errors.js:14:15)
	at Request.plumbing.callback (C:\Users\kdoyle\.vscode\extensions\peterjausovec.vscode-docker-0.1.0\node_modules\request-promise-core\lib\plumbing.js:87:29)
	at Request.RP$callback [as _callback] (C:\Users\kdoyle\.vscode\extensions\peterjausovec.vscode-docker-0.1.0\node_modules\request-promise-core\lib\plumbing.js:46:31)
	at self.callback (C:\Users\kdoyle\.vscode\extensions\peterjausovec.vscode-docker-0.1.0\node_modules\request\request.js:185:22)
	at emitOne (events.js:96:13)
	at Request.emit (events.js:191:7)
	at Request.onRequestError (C:\Users\kdoyle\.vscode\extensions\peterjausovec.vscode-docker-0.1.0\node_modules\request\request.js:877:8)
	at emitOne (events.js:101:20)
	at ClientRequest.emit (events.js:191:7)
	at TLSSocket.socketErrorListener (_http_client.js:358:9)
	at emitOne (events.js:96:13)
	at TLSSocket.emit (events.js:191:7)
	at emitErrorNT (net.js:1283:8)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)`

**Comment by StephenWeatherford** [comment]
Were you able to figure this out?  Your question isn't specific enough. For docker hub, we're hitting URL's like https://hub.docker.com/v2/…

**Comment by keithdoyle9** [comment]
Thanks Stephen. I submitted a request to have this fixed. Should be good to go after that. I appreciate the help.

**Comment by keithdoyle9** [comment]
Just to add closure to the original issue. No longer failing after having the docker hub URL whitelisted in company firewall.

**Comment by StephenWeatherford** [comment]
Thanks, appreciate your letting us know.
