### ISSUE TITLE
The extension does not work after upgrading from ` v1.26.0` to `v1.26.1`.

### ISSUE THREAD

**Issue by DeadNews** [microsoft/vscode-docker#4078]
The extension does not work after upgrading from `v1.26.0` to `v1.26.1`.
If you roll back the version, everything works.

- About vscode:

```yaml
Version: 1.82.0
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-11T16:30:45.959Z
Electron: 25.6.0
ElectronBuildId: undefined
Chromium: 114.0.5735.134
Node.js: 18.15.0
V8: 11.4.183.23-electron.0
OS: Linux x64 6.5.3-1-MANJARO
```

- Extension Host log:

```console
2023-09-20 18:28:06.347 [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-docker, startup: false, activationEvent: 'onLanguage:dockerfile'
2023-09-20 18:28:06.349 [error] Activating extension ms-azuretools.vscode-docker failed due to an error:
2023-09-20 18:28:06.349 [error] Error: Cannot find module './dist/extension.bundle'
Require stack:
- /home/deadnews/.vscode/extensions/ms-azuretools.vscode-docker-1.26.1-universal/main.js
- /usr/lib/code/out/vs/loader.js
- /usr/lib/code/out/bootstrap-amd.js
- /usr/lib/code/out/bootstrap-fork.js
- 
	at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
	at o._resolveFilename (node:electron/js2c/utility_init:2:3040)
	at Module._load (node:internal/modules/cjs/loader:927:27)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at c._load (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:135:5630)
	at m._load (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:132:29116)
	at D._load (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:99:19764)
	at Module.require (node:internal/modules/cjs/loader:1148:19)
	at g (/usr/lib/code/out/vs/loader.js:4:647)
	at Object.<anonymous> (/home/deadnews/.vscode/extensions/ms-azuretools.vscode-docker-1.26.1-universal/main.js:22:19)
	at u._compile (/usr/lib/code/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
	at Module.load (node:internal/modules/cjs/loader:1124:32)
	at Module._load (node:internal/modules/cjs/loader:965:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at c._load (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:135:5630)
	at m._load (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:132:29116)
	at D._load (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:99:19764)
	at Module.require (node:internal/modules/cjs/loader:1148:19)
	at require (node:internal/modules/cjs/helpers:110:18)
	at Function.i [as __$__nodeRequire] (/usr/lib/code/out/vs/loader.js:5:98)
	at n.rb (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:132:30295)
	at async Promise.all (index 0)
```

ref: https://github.com/microsoft/vscode-docker/releases/tag/v1.26.1

**Comment by bwateratmsft** [comment]
It seems like the extension bundle didn't install properly. Can you try uninstalling and reinstalling version 1.26.1 to see if that fixes the issue?

**Comment by DeadNews** [comment]
The `v1.26.1` installed from https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker works. 
The `v1.26.1` installed from https://open-vsx.org/extension/ms-azuretools/vscode-docker does not work.

Looks like [open-vsx.org](https://open-vsx.org/) issue.
